// components/BigGlyf.tsx
import React from "react";
import FontAwesome from "react-fontawesome";
import { Button } from "react-bootstrap";

export default function BigGlyf({ name, href, variant }) {
  return (
    <Button
      style={{ minWidth: 100 }}
      size="lg"
      variant={variant}
      href={href}
      target="_blank"
    >
      <FontAwesome name={name} />
      {/* <br />
      <small> {name}</small> */}
    </Button>
  );
}

// .vitepress/theme/components/BigGlyf.vue
<script setup lang="ts">
defineProps<{
  name: string;
  href: string;
  variant?: string;
}>();
</script>

<template>
  <a
    :class="['btn', 'btn-lg', `btn-${variant || 'primary'}`]"
    :href="href"
    target="_blank"
  >
    <i :class="['fa', `fa-${name}`]"></i>
  </a>
</template>

<style scoped>
.btn {
  min-width: 100px;
}
</style>
